#表記ゆれ
mapping_dict = {
    "BOLIVIA" : "BOLIVIA (PLURINATIONAL STATE OF)",
    "CAPE VERDE" : "CABO VERDE",
    "CÔTE D'IVOIRE" : "COTE D'IVOIRE",
    "CZECH REPUBLIC" : "CZECHIA",
    "LIBYAN ARAB JAMAHIRIYA" : "LIBYA",
    "NETHERLANDS" : "NETHERLANDS (KINGDOM OF THE)",
    "SWAZILAND" : "ESWATINI",
    "THE FORMER YUGOSLAV REPUBLIC OF MACEDONIA" : "NORTH MACEDONIA",
    "TURKEY" : "TÜRKÝYE",
    "VENEZUELA" : "VENEZUELA (BOLIVARIAN REPUBLIC OF)"
}

#かつて存在したlist_bにのみ存在する国リスト
only_b_list = [
    "YUGOSLAVIA"
]